### PR TITLE
[Code] Code Linting

### PR DESCRIPTION
**Pull request by jumatberkah**
Signed-off-by: jumatberkah <redminote5arom@gmail.com>

A Readable Code Is Better to See

### CODE REVIEW

**Comment by ProtoChuz** [comment]
@jumatberkah wau

**Comment by ProtoChuz** [comment]
@ProtoChuz dih ko ngereply

**Comment by jumatberkah** [comment]
@ProtoChuz Zzzzzz

**Comment by AyraHikari** [comment]
Why?
Btw use tabs instead of space

**Comment by jumatberkah** [comment]
@AyraHikari It is automated using code linter(black) it will match PEP8 code style

**Comment by najahiiii** [comment]
@jumatberkah

**Comment by Sunda001** [comment]
@jumatberkah P

**Pull request closed without merging**
